# Get Player data.

In this notebook we will connect to the API to download teh data of the players tio have some condittions.

In [1]:
# The expected imports

import pandas as pd
import numpy as np

# to have access to the web service
import requests

# Define the connexion.

In [2]:
# The IP of the docker server

# Mac ip
ip = "192.168.178.36"

# From external connexions. 
# ip = "saizvirtual.ddns.net"

## Define the search

In [3]:
# Define how many predictions we like to recover. The LAST PREDICTIONS

cuantos = 15

# Connect to the API

In [4]:
# URLs to connected with the app-service
# in this case the port is 

url = 'http://{}:5000/last_predictions'.format(ip)

In [5]:
url

'http://192.168.178.36:5000/last_predictions'

In [6]:
resp = requests.get(url, json={'cuantos': cuantos})

In [7]:
resp

In [8]:
resp.json()

'{"id":{"0":18,"1":10,"2":11,"3":12,"4":13,"5":14,"6":15,"7":16,"8":17,"9":1,"10":2,"11":3,"12":4,"13":5,"14":6},"item_id":{"0":1,"1":1,"2":1,"3":1,"4":1,"5":1,"6":1,"7":1,"8":1,"9":1,"10":1,"11":1,"12":1,"13":1,"14":1},"auction_type":{"0":2,"1":2,"2":2,"3":2,"4":2,"5":2,"6":2,"7":2,"8":2,"9":2,"10":2,"11":2,"12":2,"13":2,"14":2},"bid_value":{"0":154.38,"1":10.0,"2":25.0,"3":63.33,"4":100.0,"5":103.0,"6":111.0,"7":120.0,"8":151.88,"9":10.0,"10":25.0,"11":63.33,"12":100.0,"13":103.0,"14":111.0},"bid_time":{"0":0.9861114,"1":0.072051264,"2":0.07573708,"3":0.29701525,"4":0.29146087,"5":0.30494744,"6":0.90393364,"7":0.9369539,"8":0.8485984,"9":0.072051264,"10":0.07573708,"11":0.29701525,"12":0.29146087,"13":0.30494744,"14":0.90393364},"bidder_rate":{"0":1.0,"1":0.6181818,"2":0.14545454,"3":0.07272727,"4":0.58181816,"5":0.2,"6":1.0,"7":0.14545454,"8":1.0,"9":0.6181818,"10":0.14545454,"11":0.07272727,"12":0.58181816,"13":0.2,"14":1.0},"open_price":{"0":10.0,"1":10.0,"2":10.0,"3":10.0,"4":10.0,"5":10.0,"6":10.0,"7":10.0,"8":10.0,"9":10.0,"10":10.0,"11":10.0,"12":10.0,"13":10.0,"14":10.0},"rank":{"0":9,"1":1,"2":2,"3":3,"4":4,"5":5,"6":6,"7":7,"8":8,"9":1,"10":2,"11":3,"12":4,"13":5,"14":6},"num_bids":{"0":9,"1":9,"2":9,"3":9,"4":9,"5":9,"6":9,"7":9,"8":9,"9":9,"10":9,"11":9,"12":9,"13":9,"14":9},"prev_bid_value":{"0":151.88,"1":10.0,"2":10.0,"3":25.0,"4":63.33,"5":100.0,"6":103.0,"7":111.0,"8":120.0,"9":10.0,"10":10.0,"11":25.0,"12":63.33,"13":100.0,"14":103.0},"prev_bid_value_avg":{"0":67.79125,"1":10.0,"2":10.0,"3":10.0,"4":15.0,"5":27.0825,"6":41.666,"7":51.888332,"8":60.33286,"9":10.0,"10":10.0,"11":10.0,"12":15.0,"13":27.0825,"14":41.666},"bid_value_delta":{"0":2.5,"1":0.0,"2":15.0,"3":38.33,"4":36.67,"5":3.0,"6":8.0,"7":9.0,"8":31.88,"9":0.0,"10":15.0,"11":38.33,"12":36.67,"13":3.0,"14":8.0},"model_version":{"0":"XGB.0.1","1":"XGB.0.1","2":"XGB.0.1","3":"XGB.0.1","4":"XGB.0.1","5":"XGB.0.1","6":"XGB.0.1","7":"XGB.0.1","8":"XGB.0.1","9":"XGB.0.1","10":"XGB.0.1","11":"XGB.0.1","12":"XGB.0.1","13":"XGB.0.1","14":"XGB.0.1"},"created_at":{"0":1710894220971,"1":1710894220971,"2":1710894220971,"3":1710894220971,"4":1710894220971,"5":1710894220971,"6":1710894220971,"7":1710894220971,"8":1710894220971,"9":1710891528362,"10":1710891528362,"11":1710891528362,"12":1710891528362,"13":1710891528362,"14":1710891528362}}'

In [9]:
import json
df = pd.DataFrame(json.loads(resp.json()))

In [11]:
from datetime import datetime
# df['created_at'] = df['created_at'].apply(lambda x: datetime.fromtimestamp(x))

In [12]:
for i in df['created_at']:
    print(datetime.fromtimestamp(i))

ValueError: year 56186 is out of range

In [13]:
df

,id,item_id,auction_type,bid_value,bid_time,bidder_rate,open_price,rank,num_bids,prev_bid_value,prev_bid_value_avg,bid_value_delta,model_version,created_at
0,18,1,2,154.38,0.986111,1.000000,10.0,9,9,151.88,67.791250,2.50,XGB.0.1,1710894220971
1,10,1,2,10.00,0.072051,0.618182,10.0,1,9,10.00,10.000000,0.00,XGB.0.1,1710894220971
2,11,1,2,25.00,0.075737,0.145455,10.0,2,9,10.00,10.000000,15.00,XGB.0.1,1710894220971
3,12,1,2,63.33,0.297015,0.072727,10.0,3,9,25.00,10.000000,38.33,XGB.0.1,1710894220971
4,13,1,2,100.00,0.291461,0.581818,10.0,4,9,63.33,15.000000,36.67,XGB.0.1,1710894220971
5,14,1,2,103.00,0.304947,0.200000,10.0,5,9,100.00,27.082500,3.00,XGB.0.1,1710894220971
6,15,1,2,111.00,0.903934,1.000000,10.0,6,9,103.00,41.666000,8.00,XGB.0.1,1710894220971
7,16,1,2,120.00,0.936954,0.145455,10.0,7,9,111.00,51.888332,9.00,XGB.0.1,1710894220971
8,17,1,2,151.88,0.848598,1.000000,10.0,8,9,120.00,60.332860,31.88,XGB.0.1,1710894220971
9,1,1,2,10.00,0.072051,0.618182,10.0,1,9,10.00,10.000000,0.00,XGB.0.1,1710891528362
10,2,1,2,25.00,0.075737,0.145455,10.0,2,9,10.00,10.000000,15.00,XGB.0.1,1710891528362
11,3,1,2,63.33,0.297015,0.072727,10.0,3,9,25.00,10.000000,38.33,XGB.0.1,1710891528362
12,4,1,2,100.00,0.291461,0.581818,10.0,4,9,63.33,15.000000,36.67,XGB.0.1,1710891528362
13,5,1,2,103.00,0.304947,0.200000,10.0,5,9,100.00,27.082500,3.00,XGB.0.1,1710891528362
14,6,1,2,111.00,0.903934,1.000000,10.0,6,9,103.00,41.666000,8.00,XGB.0.1,1710891528362